CREATE DATABASE IF NOT EXISTS portal_faeterj CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE portal_faeterj;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(120) UNIQUE,
  senha_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS noticias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  conteudo TEXT NOT NULL,
  autor VARCHAR(100) NOT NULL,
  data_publicacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eventos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(200) NOT NULL,
  descricao TEXT,
  local VARCHAR(150),
  inicio DATETIME NOT NULL,
  fim DATETIME NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);